services:
  api:
    build: .
    container_name: churn_api
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: your_password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: churn_ltv_db
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: churn_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: churn_ltv_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase
    container_name: churn_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: standalone

volumes:
  postgres_data:
